name: "Build Armbian"

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Armbian
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_release: "jammy"
          armbian_target: "nanopi-r1s-h5"
          armbian_branch: "current"
          armbian_build_minimal: "yes"
